// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8gXL0TbJ_R_74hMl2nYMsBiGCTOFHXVo',
    appId: '1:281094283524:web:0ec61cb4e17b1313093051',
    messagingSenderId: '281094283524',
    projectId: 'my-emu-app',
    authDomain: 'my-emu-app.firebaseapp.com',
    storageBucket: 'my-emu-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEsg5PqOggtv_rqaY6k5euu2REzwjT3zM',
    appId: '1:281094283524:android:24f56d64d4ab7607093051',
    messagingSenderId: '281094283524',
    projectId: 'my-emu-app',
    storageBucket: 'my-emu-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSu6L87gr4zj2WycjMxbUR-pS4ArzCZF4',
    appId: '1:281094283524:ios:b167d307647fb98f093051',
    messagingSenderId: '281094283524',
    projectId: 'my-emu-app',
    storageBucket: 'my-emu-app.appspot.com',
    iosClientId: '281094283524-oeq4rbtc5i35ilfe9uqfr2t7teuh4p1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoApp',
  );
}
